### PR TITLE
Add sync for e-bikes

### PR DESCRIPTION
**Pull request by Mattti0**
## Description of change
Add support to synchronize also e-bike rides

As Kilometrikisa supports only one activity per day, this will mark daily entry as electric if there is at least one ride with electric bike

## Related issue
[Add support for electric bikes #22](https://github.com/jaamo/strava2kilometrikisa/issues/22) 

## How has this been tested?
Tested by using local development environment, Windows 10, node version 12.4.1

## Screenshots (if appropriate):
image
image
image

### CODE REVIEW

**Comment by Mattti0** [comment]
Maybe this could be improved by asking user if he/she wants to sync also electric bike rides.

Todo: add another toggle to front page (with autosync) and add `syncebike: { type: Boolean }` to UserSchema in UserModel.js and utilize that in needed places

**Comment by juhari** [comment]
Thanks for the PR! I was looking for this feature and stumbled into the PR. I tested it on my own machine and I can confirm that this seems to be working.

**Comment by Mattti0** [comment]
2021-05-07 13_56_27-Strava2kilometrikisa — Mozilla Firefox (Private Browsing)

**Comment by Mattti0** [comment]
@jaamo @onefastsnail this should be now ready for review. I don't have e-bike or autosync environment so it's bit hard to myself to test this more deeply but feel free to comment and I will do needed updates! 😊

**Comment by onefastsnail** [comment]
Hey @Mattti0, I am sorry about the delay on this one, been a busy time at work and with the family 😄.

I will get onto testing this one this week! 

Thanks for the PR 🙏

**Comment by mikko** [comment]
@onefastsnail I finally found time to test this and it does seem to be working as assumed. Tested with test data with and without e-bike type in Strava. :bike:

**Review by onefastsnail — APPROVED** [review]
Looks good!

Thanks again for the PR, and sorry for the delay 🙏 .

**Comment by onefastsnail** [comment]
Once built on UAT, will give it one more test then promote to LIVE 😄. Should be done within the hour.

**Comment by onefastsnail** [comment]
Deployed! Let me know if you have any issues.

**Pull request merged**
