### PR TITLE
Added support to update expired Strava token

### PR DESCRIPTION
**Pull request by Mattti0**
Updated activity scope

### CODE REVIEW

**Comment by hugovk** [comment]
Sounds like this should fix https://github.com/jaamo/strava2kilometrikisa/issues/30.

**Comment by jaamo** [comment]
Thanks for your input! I'll test this :) Let's see if it works.

**Comment by Mattti0** [comment]
Found out that this will not fix sync entirely. Access token expires every six hours and new should be queried with refresh token. https://developers.strava.com/docs/authentication/#refreshingexpiredaccesstokens

**Comment by Mattti0** [comment]
I'm not sure if this works right out of the box because I don't have local environment configured atm

**Pull request merged**
