### PR TITLE
Strava token refresh uses promise, so needed to fix method

### PR DESCRIPTION
**Pull request by Mattti0**
Moved also updateToken to manual sync preview to do update also before preview.

Not sure if #33  is caused by that method but I have a feeling that it might be related

### CODE REVIEW

**Comment by hugovk** [comment]
I'm also not getting any automatic syncing, is that a different issue?

**Comment by Mattti0** [comment]
I guess that it is same issue

**Comment by hugovk** [comment]
@jaamo Any thoughts on this? Thanks!

**Comment by onefastsnail** [comment]
Good catch @Mattti0 with the return of a promise. 

I have merged this into #34 and also refactored the usage of the `updateToken` so that we only continue to query the Strava APIs once the promise resolves ie. retrieves a token when at all necessary. As before due to the asynchronous nature of the `strava-v3` API we could run into a condition where the Strava API query is not using the updated token.

**Pull request closed without merging**
